[package]
name = "actor_model"
version = "0.1.0"
authors = ["Leon Busse <leon.busse@br.de>"]
edition = "2018"

[dependencies]
tokio = "*"
futures = "*"
tokio-serde-json = "*"
serde_json = "*"
bytes = "*"