[package]
name = "actor_model"
version = "0.1.0"
authors = ["Leon Busse <leon.busse@br.de>"]
edition = "2018"

[dependencies]
tokio = "*"
futures = "*"
bytes = "0.4.11"
config = "0.9.2"
serde_json = "1.0.36"
tokio-serde-json = "0.2.0"