version: "2"

services:
  master:
    build: ./docker-image
    container_name: master
    # networks:
    #   - mpi
    ports:
      - "2222:22"
    volumes:
      - hosts:/hosts
  node:
    build: ./docker-image
    command: ./compose-start.sh
    # networks:
    #   - mpi
    volumes_from:
      - master

networks:
  default:
    driver: bridge
  # mpi:
  #   external: true

volumes:
  hosts:
